<a href="https://colab.research.google.com/github/praharikareddy/ML_23AG1A66E7/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr2=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr2)

[[1 2 3 4 5]
 [4 5 6 7 8]]


In [6]:
arr3=np.array([[[1,2,3,4,5],[4,5,6,7,8],[10,11,12,13,14]]])
print(arr3)

[[[ 1  2  3  4  5]
  [ 4  5  6  7  8]
  [10 11 12 13 14]]]


In [7]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [8]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(2, 5)
(1, 3, 5)


In [9]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
int64
int64


In [10]:
print(arr1.size)
print(arr2.size)
print(arr3.size)

5
10
15


In [11]:
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

8
8
8


In [12]:
arr4=np.array([1,2,3,4,5])
x=np.mean(arr4)
print(x)
y=np.sum(arr4)
print(y)
z=np.median(arr4)
print(z)
k=np.std(arr4)
print(k)

3.0
15
3.0
1.4142135623730951


In [13]:
print(arr1.data)
print(arr2.data)
print(arr3.data)

In [14]:
array1=np.array([1,3,5,7,9])
print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


In [15]:
array1[1]=10
print(array1)

[ 1 10  5  7  9]


In [16]:
array1=np.array([[1,3,5,7],
                 [9,11,13,15],
                 [2,4,6,8]])

element1=array1[1,3]
print("4th Element at 2nd Row:",element1)

element2=array1[0,1]
print("2nd Element at 1st Row:",element2)

4th Element at 2nd Row: 15
2nd Element at 1st Row: 3


In [17]:
marks=np.array([76,78,81,66,85])
std_marks=np.percentile(marks,50)
print(std_marks)

78.0


In [18]:
marks=np.array([76,78,81,66,85])
std_marks=np.min(marks)
print(std_marks)

66


In [19]:
marks=np.array([76,78,81,66,85])
std_marks=np.max(marks)
print(std_marks)

85
