<a href="https://colab.research.google.com/github/praharikareddy/ML_23AG1A66E7/blob/main/Statistical_Measures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Statistical Measures**
-Central Tendency Measures
-Measures of Dispersion

In [1]:
import numpy as np
from statistics import mean, median, mode

# Example data
data=[2,4,4,4,5,5,7,9]

# Central Tendency Measures
print("Mean:", mean(data))            # Mean
print("Median:", median(data))        # Median
print("Mode:", mode(data))            # Mode

# Measures of Dispersion
print("Variance:", np.var(data))               # Variance(Population)
print("Standard Deviation:", np.std(data))     # Standard Deviation(Population)

Mean: 5
Median: 4.5
Mode: 4
Variance: 4.0
Standard Deviation: 2.0


**Math library**
1. Number Functions

In [3]:
import math
print(math.ceil(2.3))
print(math.floor(2.7))
print(math.trunc(8.9))

3
2
8


2. Power and Logarithmic Functions

In [4]:
print(math.pow(2,3))
print(math.sqrt(16))
print(math.exp(2))
print(math.log(100,10))

8.0
4.0
7.38905609893065
2.0


3. Trigonometric Functions

In [5]:
print(math.sin(math.pi/2))
print(math.cos(0))
print(math.tan(math.pi/4))
print(math.radians(90))
print(math.degrees(math.pi))

1.0
1.0
0.9999999999999999
1.5707963267948966
180.0


4. Special Functions

In [6]:
print(math.factorial(5))
print(math.gcd(20,8))
print(math.fabs(-7.5))

120
4
7.5


5. Constants

In [7]:
print(math.pi)
print(math.e)

3.141592653589793
2.718281828459045


**SciPy**

In [8]:
# Print the constant value pf PI:

from scipy import constants

print(constants.pi)

print(constants.yotta)    #1e+24
print(constants.zetta)    #1e+21
print(constants.exa)      #1e+18
print(constants.peta)     #1000000000000000.0
print(constants.tera)     #1000000000000.0
print(constants.giga)     #1000000000.0
print(constants.mega)     #1000000.0
print(constants.kilo)     #1000.0
print(constants.hecto)    #100.0
print(constants.deka)     #10.0
print(constants.deci)     #0.1
print(constants.centi)    #0.01
print(constants.milli)    #0.001
print(constants.micro)    #1e-06
print(constants.nano)     #1e-09
print(constants.pico)     #1e-12
print(constants.femto)    #1e-15
print(constants.atto)     #1e-18
print(constants.zepto)    #1e-21

3.141592653589793
1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21


In [9]:
#Binary Prefixes:
#Return the specified unit in bytes (e.g. kibi returns 1024)

print(constants.kibi)    #1024
print(constants.mebi)    #1048576
print(constants.gibi)    #1073741824
print(constants.tebi)    #1099511627776
print(constants.pebi)    #1125899906842624
print(constants.exbi)    #1152921504606846976
print(constants.zebi)    #1180591620717411303424
print(constants.yobi)    #1208925819614629174706176

1024
1048576
1073741824
1099511627776
1125899906842624
1152921504606846976
1180591620717411303424
1208925819614629174706176


In [10]:
#Connected Components
#Find all of the connected components with the connected_components() method.
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(connected_components(newarr))

(1, array([0, 0, 0], dtype=int32))


**Dijkstra**

In [11]:
#Find the shortest path from element 1 to 2:

import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(dijkstra(newarr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


In [12]:
#Floyd Warshall
#Use the floyd_warshall() method to find shortest path between all pairs of elements.

#Find the shortest path between all pairs of elements:

import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


In [15]:
#Bellman Ford
#The bellman_ford() method can also find the shortest path between all pairs of elements, but this method can handle negative weights as well.

#Find shortest path from element 1 to 2 with given graph with a negative weight:

import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
  [0, -1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([ 0., -1.,  2.]), array([-9999,     0,     0], dtype=int32))
